### ISSUE TITLE
Support usage of extrinsic functions with custom variables

### ISSUE THREAD

**Issue by klindklind** [theburningmonk/serverless-plugin-extrinsic-functions#4]
I really missed "startsWith" function in serverless.yml and then fortunately I found your plugin!

However would it be possible to use these functions when declaring custom variables in serverless.yml?

If I define

```
service: my-service

custom:
  isDevStage:
    - Fn::StartsWith: [ ${opt:stage}, dev ]
```

into my serverless.yml I get

```
missed comma between flow collection entries in ... 
- Fn::StartsWith: [ ${opt:stage}, dev ]
                               ^
```

Would it also be possible to cast that Fn::StartsWith function return value to string?

If I'd be able to pass that ${opt:stage} value for that custom isDevStage variable so it would be evaluated to this

```
service: my-service

custom:
  isDevStage:
    - Fn::StartsWith: [ dev1234, dev ]
```

I'd end up with

```
Trying to populate non string value into a string for variable ${self:custom.isDevStage}. Please make sure the value of the property is a string.
```

**Comment by theburningmonk** [comment]
hey @klindklind sorry I missed this, the fix here is to just put quotes around `${opt:stage}`:

```
service: my-service

custom:
  isDevStage:
    - Fn::StartsWith: [ "${opt:stage}", dev ]
```

**Comment by theburningmonk** [comment]
I've fixed the docs so that it's clear

**Comment by klindklind** [comment]
Aah thanks! I ended up working around this by using some other plugin but good to know that the thing I described is supported after all. I'll close this.
